### PR TITLE
Support for converting tiles to/from quadkeys.

### PR DESCRIPTION
**Pull request by youngpm**
This addresses #50.

### CODE REVIEW

**Comment by youngpm** [comment]
Lemme know if you want anything changed, fixed up, etc!

**Comment by dnomadb** [comment]
Awesome, thanks @youngpm ! I've manually had to write this many times (all using `numpy` tho), so the functionality is much appreciated.

I'm going to run this against [`tilebelt`](https://github.com/mapbox/tilebelt) to verify all is good, but other than that - 👍 .

**Comment by dnomadb** [comment]
Using https://gist.github.com/2d1089078fe09e6c1c5b3844e9f850e0 as `test.py` and https://gist.github.com/eb6a74efea5e83614b9c081708578ab4 as `test.js`:

This PR:
```
» echo '[0, 0, 0]' | mercantile children --depth 5 | python test.py > /tmp/mercqk.txt
```
and tilebelt:
```
» echo '[0, 0, 0]' | mercantile children --depth 5 | node test.js > /tmp/tilebeltqk.txt
```
they are the same:
```
» diff /tmp/mercqk.txt /tmp/tilebeltqk.txt 

```
I think this is good to go.

**Comment by dnomadb** [comment]
@youngpm can you add a quick example in the readme? Other than that, this is ready to merge.

**Comment by youngpm** [comment]
@dnomadb should be good!

**Comment by sgillies** [comment]
@youngpm Would you be willing to change `qk` to `quadkey`? We've got some shorthand function names like `ul` and `xy` but I'd like to draw the line there.

**Comment by youngpm** [comment]
No prob!  I originally had it like that and was "inspired" by the other short names :)

**Comment by jwass** [comment]
`__all__` still contains the `qk` method names.

https://github.com/mapbox/mercantile/blob/8b5aeeb0e19c0f700b7102317f6193da17c232b5/mercantile/__init__.py#L9

**Comment by youngpm** [comment]
My bad, I've just put in another PR fixing this.

**Pull request merged**
