### PR TITLE
mercantile tile point input

### LINKED ISSUE #48: mercantile tiles gives incorrect results for points
At any zoom level, a point can only intersect a single tile. The help text of `mercantile tiles` claims to take "lng/lat point, bounding box, or GeoJSON objects". But the results are incorrect for points.

```
$ echo '{"type":"geometry","coordinates":[14.0859, 5.798]}' | mercantile tiles 5 | wc -l
      33
$ echo "[14.0859, 5.798]" | mercantile tiles 5 | wc -l
      33
```

If we create a tiny bounding box using the point coordinate, we get the correct results.

```
$ echo "[14.0859, 5.798, 14.0860, 5.799]" | mercantile tiles 5 | wc -l
       1
```

### PR DESCRIPTION
**Pull request by perrygeo**
If point input, buffer by epsilon to get a valid bbox.

fixes #48

### CODE REVIEW

**Comment by perrygeo** [comment]
@sgillies, ready for :eyes:, probably worth doing a 0.8.4 release

**Comment by jwass** [comment]
Hi @perrygeo - sorry to jump in here :)

`mercantile.tiles()` is able to handle bounds with zero width/height so it might be better to just pass them through in that case...? Adding the padding on the input point can still cause the bounds to cross a tile boundary. A tile corner breaks the "one point to one tile" assumption using the code in this PR:

```
$ echo "[11.25, 0.0]" | mercantile tiles 5
[16, 15, 5]
[16, 16, 5]
[17, 15, 5]
[17, 16, 5]
```

All this raises the question of what the behavior should be when a point lies exactly on a tile boundary, and can the behavior be consistent with the round-trip expectation used to justify shrinking the bbox in the first place?

**Comment by perrygeo** [comment]
@jwass good point, I think we need to ditch my "one point to one tile assumption" since a corner point would technically intersect 4 tiles. I think that's fine and expected behavior. 

So the question is, do we need to buffer to achieve that? Looks like yes unless we want to change the behavior of `mercantile.tiles`:
```
>>> from mercantile import tiles
>>> list(tiles(11.25, 0.0, 11.25, 0.0, [5]))
[Tile(x=17, y=16, z=5)]
>>> list(tiles(11.2499999999, -0.0000000001, 11.2500000001, 0.000000001, [5]))
[Tile(x=16, y=15, z=5),
 Tile(x=16, y=16, z=5),
 Tile(x=17, y=15, z=5),
 Tile(x=17, y=16, z=5)]
```

**Comment by jwass** [comment]
@perrygeo I definitely agree that a point exactly on a tile boundary should count as intersecting both tiles. I think the problem with fixing that assumption is this [test case](https://github.com/mapbox/mercantile/blob/master/tests/test_cli.py#L139) which enforces:

```
$ echo "[2331,1185,12]" | mercantile shapes | mercantile tiles 12
[2331, 1185, 12]
```

If a point on a boundary intersects both tiles, shouldn't the boundary of the tile then intersect all adjacent tiles? The result should be the center tile and its 8 surrounding tiles..? Is the round-trip test case and assumption wrong?

Either way I think `tiles()` should reflect the desired output and the CLI should just pass the values through. Otherwise the CLI and the library will have different behavior on identical inputs. Also, the padding is bound to cause trouble on some edge cases at scale. If `tiles()` had an explicit check, then the padding can be removed entirely - so I think the fix should be in `tiles()`, not the CLI.

I've mostly been using the library, not the CLI, but figured I'd chime in. Feel free to ignore, esp if you need a quick fix :)

**Comment by perrygeo** [comment]
@jwass so if we're going to change the edge behavior, let's do it at the python API level in a different PR.

For this PR, I'll remove the buffer so the behavior between CLI and python API is consistent.

**Comment by jwass** [comment]
Sounds good.

**Comment by sgillies** [comment]
@perrygeo @jwass this is good to go?

**Comment by jwass** [comment]
👍

**Pull request merged**
